version: '3.8'

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    ports:
      - "5678:5678"
    user: root  # <--- NECESARIO para que n8n tenga permiso de usar Docker
    volumes:
      - ./n8n-local-data:/home/node/.n8n
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=https://${CODESPACE_NAME}-5678.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}/
